### ISSUE TITLE
CLI error calculating RTT when any latency point is `None`

### ISSUE THREAD

**Issue by RascalTwo** [dgzlopes/tcp-latency#14]
When executing the CLI with more then one run, if a single `latency_point` in the `latency_points` list is None, then when the last run is reached, an error is thrown:

```bash
> tcp_latency example.does.not.exist
tcp-latency example.does.not.exist
example.does.not.exist: tcp seq=0 port=443 timeout=5 failed
example.does.not.exist: tcp seq=1 port=443 timeout=5 failed
example.does.not.exist: tcp seq=2 port=443 timeout=5 failed
example.does.not.exist: tcp seq=3 port=443 timeout=5 failed
example.does.not.exist: tcp seq=4 port=443 timeout=5 failed
--- example.does.not.exist tcp-latency statistics ---
5 packets transmitted
Traceback (most recent call last):
  File "tcp_latency/tcp_latency.py", line 154, in <module>
    _main()
  File "tcp_latency/tcp_latency.py", line 143, in _main
    measure_latency(
  File "tcp_latency/tcp_latency.py", line 91, in measure_latency
    f'rtt min/avg/max = {min(latency_points)}/{mean(latency_points)}/{max(latency_points)} ms',   # noqa: E501
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

None of the three methods - `min`, `mean`, or `max` - are able to accept iterables that contain `None`.

The behavior is the same when just one of the points are `None` and the rest are valid `floats`s.

> Due to another issue, the last `latency_point` is not included in RTT calculations, therefore if only the last point that is `None`, this error is not thrown.

**Comment by RascalTwo** [comment]
If you want, I can also solve the `last latency_point not being included in RTT calculations` issue with this PR too - should only involve moving the

```python
latency_points.append(last_latency_point)
```

line up before the
```python
if human_output:
```
line.
